// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/proto/TransferProtocol.proto

package netty.protocols.protobuf;

public final class FastTransfer {
  private FastTransfer() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_netty_Request_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_netty_Request_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n/src/main/resources/proto/TransferProto" +
      "col.proto\022\005netty\"A\n\007Request\022\021\n\004path\030\001 \001(" +
      "\tH\000\210\001\001\022\021\n\004data\030\002 \001(\014H\001\210\001\001B\007\n\005_pathB\007\n\005_d" +
      "ataB*\n\030netty.protocols.protobufB\014FastTra" +
      "nsferP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_netty_Request_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_netty_Request_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_netty_Request_descriptor,
        new java.lang.String[] { "Path", "Data", "Path", "Data", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
