// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/proto/TransferProtocol.proto

package netty.protocols.protobuf;

public interface RequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:netty.Request)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string path = 1;</code>
   * @return Whether the path field is set.
   */
  boolean hasPath();
  /**
   * <code>optional string path = 1;</code>
   * @return The path.
   */
  java.lang.String getPath();
  /**
   * <code>optional string path = 1;</code>
   * @return The bytes for path.
   */
  com.google.protobuf.ByteString
      getPathBytes();

  /**
   * <code>optional bytes data = 2;</code>
   * @return Whether the data field is set.
   */
  boolean hasData();
  /**
   * <code>optional bytes data = 2;</code>
   * @return The data.
   */
  com.google.protobuf.ByteString getData();
}
