// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/proto/DataStruct.proto

package netty.listen;

/**
 * Protobuf enum {@code netty.FileType}
 */
public enum FileType
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>F = 0;</code>
   */
  F(0),
  /**
   * <code>D = 1;</code>
   */
  D(1),
  /**
   * <code>B = 2;</code>
   */
  B(2),
  /**
   * <code>C = 3;</code>
   */
  C(3),
  /**
   * <code>S = 4;</code>
   */
  S(4),
  /**
   * <code>P = 5;</code>
   */
  P(5),
  /**
   * <code>L = 6;</code>
   */
  L(6),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>F = 0;</code>
   */
  public static final int F_VALUE = 0;
  /**
   * <code>D = 1;</code>
   */
  public static final int D_VALUE = 1;
  /**
   * <code>B = 2;</code>
   */
  public static final int B_VALUE = 2;
  /**
   * <code>C = 3;</code>
   */
  public static final int C_VALUE = 3;
  /**
   * <code>S = 4;</code>
   */
  public static final int S_VALUE = 4;
  /**
   * <code>P = 5;</code>
   */
  public static final int P_VALUE = 5;
  /**
   * <code>L = 6;</code>
   */
  public static final int L_VALUE = 6;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static FileType valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static FileType forNumber(int value) {
    switch (value) {
      case 0: return F;
      case 1: return D;
      case 2: return B;
      case 3: return C;
      case 4: return S;
      case 5: return P;
      case 6: return L;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<FileType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      FileType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<FileType>() {
          public FileType findValueByNumber(int number) {
            return FileType.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return netty.listen.FileProto.getDescriptor().getEnumTypes().get(0);
  }

  private static final FileType[] VALUES = values();

  public static FileType valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private FileType(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:netty.FileType)
}

