// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/proto/DataStruct.proto

package netty.listen;

public interface FileStructOrBuilder extends
    // @@protoc_insertion_point(interface_extends:netty.FileStruct)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.netty.FileType type = 1;</code>
   * @return The enum numeric value on the wire for type.
   */
  int getTypeValue();
  /**
   * <code>.netty.FileType type = 1;</code>
   * @return The type.
   */
  netty.listen.FileType getType();

  /**
   * <code>.netty.FileEvent event = 2;</code>
   * @return The enum numeric value on the wire for event.
   */
  int getEventValue();
  /**
   * <code>.netty.FileEvent event = 2;</code>
   * @return The event.
   */
  netty.listen.FileEvent getEvent();

  /**
   * <code>string path = 3;</code>
   * @return The path.
   */
  java.lang.String getPath();
  /**
   * <code>string path = 3;</code>
   * @return The bytes for path.
   */
  com.google.protobuf.ByteString
      getPathBytes();

  /**
   * <code>bytes data = 4;</code>
   * @return The data.
   */
  com.google.protobuf.ByteString getData();
}
