// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/proto/DataStruct.proto

package netty.listen;

/**
 * Protobuf enum {@code netty.FileEvent}
 */
public enum FileEvent
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>CREATE = 0;</code>
   */
  CREATE(0),
  /**
   * <code>DELETE = 1;</code>
   */
  DELETE(1),
  /**
   * <code>MODIFY = 2;</code>
   */
  MODIFY(2),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>CREATE = 0;</code>
   */
  public static final int CREATE_VALUE = 0;
  /**
   * <code>DELETE = 1;</code>
   */
  public static final int DELETE_VALUE = 1;
  /**
   * <code>MODIFY = 2;</code>
   */
  public static final int MODIFY_VALUE = 2;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static FileEvent valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static FileEvent forNumber(int value) {
    switch (value) {
      case 0: return CREATE;
      case 1: return DELETE;
      case 2: return MODIFY;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<FileEvent>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      FileEvent> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<FileEvent>() {
          public FileEvent findValueByNumber(int number) {
            return FileEvent.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return netty.listen.FileProto.getDescriptor().getEnumTypes().get(1);
  }

  private static final FileEvent[] VALUES = values();

  public static FileEvent valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private FileEvent(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:netty.FileEvent)
}

